# Generated by Django 3.2.2 on 2022-12-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_marks',
            field=models.PositiveSmallIntegerField(verbose_name='Total marks'),
        ),
    ]
