# Generated by Django 3.2.2 on 2022-12-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_pass',
            field=models.BooleanField(default=True, verbose_name='Pass?'),
        ),
    ]
